### ISSUE TITLE
[TASK: CLIENT] 회원가입 페이지 구현

### ISSUE THREAD

**Issue by yuliepie** [Elice-PnP/irumi#10]
# Task
- Type: `Client`
- Parent Feature: #9
- Description: 회원가입 페이지 만들기

## Todo
- [x] 필수로 이메일, 비밀번호, 비번확인, 이름을 입력받는다
- [ ] 선택으로 닉네임을 입력받는다
- [ ] 비밀번호는 8자이상, 영문과 숫자 포함
- [ ] 로그인으로 돌아가기 버튼
- [ ] 회원가입 완료 버튼

## Estimated Time
`5 hrs`
