### ISSUE TITLE
[TASK: CLIENT] React 폴더 구조 만들기

### ISSUE THREAD

**Issue by yuliepie** [Elice-PnP/irumi#16]
# Task
- Type: `Client`
- Parent Feature: `None`
- Description: React App의 폴더구조를 대강 만들고, create-react-app의 필요없는 요소들 정리.

## Todo
- [x] 페이지(View)별로 폴더구조 짜기
- [x] 전체적 폴더 구조를 짠후, 한 두가지 view 디렉터리를 예시로 추가
- [x] 리액트앱에 기본으로 생성되는 요소들 제거하기

## Estimated Time
`2 hrs`
