### ISSUE TITLE
[TASK: CLIENT] Common Page Layout 구성

### ISSUE THREAD

**Issue by yuliepie** [Elice-PnP/irumi#36]
# Task
- Type: `Client`
- Parent Feature: #21 #23 
- Description: 상단바, 하단탭을 이용한 공통 페이지 레이아웃 구현

## Todo
- [x] 상단바와 하단탭을 하나의 레이아웃으로 묶어 페이지를 감쌀수 있는 구조로 만들기
### 하단탭
- [x] 목표, 노트, 그룹 탭 만들기
- [x] 선택되어 있는 탭 표시
- [x] 클릭하면 해당 페이지로 이동
### 상단바
- [x] 사이드바 버튼 표시
- [x] 로고 위치 지정
- [x] 앞으로 상단바에 필요한 버튼들이 추가 될수 있는 프레임워크를 만들기

## Estimated Time
`12 hrs`
