### ISSUE TITLE
[TASK: CLIENT] LoginPage View 구성

### ISSUE THREAD

**Issue by seunghwanlee1234** [Elice-PnP/irumi#41]
# Task
- Type: `Client`
- Parent Feature: #19 
- Description: LoginPage를 구성하는 Layout 구현

## Todo
- [x] 필수로 이메일, 비번 입력받기
- [x] 이메일 형식 체크
- [ ] 내 정보 기억하기' 체크버튼 → 누르면 로그인 상태 유지됨
- [ ] 모든 정보가 입력되면 로그인 시키고 ⇒ 목표페이지(메인) 으로 이동
- [x] 회원가입페이지로 이동 버튼

## Estimated Time
`hrs`
