### ISSUE TITLE
[TASK: SERVER] Goal 모델 작성

### ISSUE THREAD

**Issue by yuliepie** [Elice-PnP/irumi#48]
# Task
- Type: `Server`
- Parent Feature: #18 
- Description: 목표를 담는 Goal 모델 만들기

## Todo
- [ ] db schema 참고해서 모델을 작성
- [ ] foreign key로 유저아이디와 연결해주기
- [ ] User model 에 relationship 추가

## Estimated Time
`3 hrs`
