### ISSUE TITLE
[TASK: CLIENT] 목표 홈페이지 구현

### ISSUE THREAD

**Issue by HunKimADev** [Elice-PnP/irumi#49]
# Task
- Type: `Client`
- Parent Feature: #25 
- Description: 목표 홈페이지 구현하기

## Todo
- [x] 달력
  - [x] 달력 주단위로 표시
  - [x] 날짜 클릭시 해당날짜로 이동
  - [x] 달력 우측 상단에 클릭가능한 캘린더 표시
  - [x] 달력 좌측 상단에 선택된 날짜 표시
  - [x] 달력에 현재 선택된 날짜 하이라이트
- [x] 목표 카테고리 오늘 / 이번 주 / 이번 달 단위로 구분
  - [x] +-로 진행도 수정 기능 구현
- [x] 오늘의 할일 (To do list) 구현
  - [x] 체크박스로 done 표시 

## Estimated Time
` 5 hrs`
